In [1]:
import numpy as np

In [3]:
from sklearn.preprocessing import MinMaxScaler

In [5]:
data =np.random.randint(0,100,(10,2))

In [6]:
data

array([[73, 34],
       [75,  6],
       [86,  8],
       [78, 77],
       [54, 67],
       [35, 10],
       [60,  2],
       [24, 56],
       [ 1, 62],
       [34, 90]])

In [7]:
scaler_model = MinMaxScaler()

In [8]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [9]:
scaler_model.fit(data)

/Users/harishankar/anaconda/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [10]:

scaler_model.transform(data)

array([[ 0.84705882,  0.36363636],
       [ 0.87058824,  0.04545455],
       [ 1.        ,  0.06818182],
       [ 0.90588235,  0.85227273],
       [ 0.62352941,  0.73863636],
       [ 0.4       ,  0.09090909],
       [ 0.69411765,  0.        ],
       [ 0.27058824,  0.61363636],
       [ 0.        ,  0.68181818],
       [ 0.38823529,  1.        ]])

In [11]:
import pandas as pd

In [14]:
df = pd.DataFrame(data=np.random.randint(0,101,(50,4)), columns=['f1','f2','f3','label'])

In [15]:
df

f1   f2  f3  label
0   65   38  94     96
1   65   59  41     55
2   18   69  75     63
3   30   22  86     26
4   83   19  43      3
5   20   95  64     30
6   18   24   0     17
7   55   24   5     94
8   53   83  71     27
9   30   71  99     87
10  28   64  10     88
11  45    8   4     29
12  41   30  51     60
13  11   59  45     19
14  50   87   1     57
15  13   74  57     73
16  39   28  26     95
17  10   90  45     91
18  30   14  88     25
19  70   60  77     54
20  20   89  73     30
21  73   55  14     55
22  61   25  93     19
23  19   34  63      1
24  47   58  72     12
25   7   90   7     97
26  13   38  10     13
27  52   61  72      3
28  30   99  98     91
29  86   48  98     89
30  22   85  95     46
31  16   11  33     12
32  80   42  83     67
33  88   23  72     71
34   7   10  61     33
35  96   30  26     90
36  32  100  34      9
37  81   73  64     73
38  23   69  64     66
39  38   90  81     29
40  47   18  27     47
41  39   48  99     77
42  54   29  33     46
43   8    2  94     99
44  71   52  87     34
45  30    6  96     59
46  82   27  59     44
47   1   67  75     78
48  90   79  89     81
49  15   95  28     15

In [16]:
x = df[['f1','f2','f3']]

In [17]:
y = df[['label']]

In [18]:
y

label
0      96
1      55
2      63
3      26
4       3
5      30
6      17
7      94
8      27
9      87
10     88
11     29
12     60
13     19
14     57
15     73
16     95
17     91
18     25
19     54
20     30
21     55
22     19
23      1
24     12
25     97
26     13
27      3
28     91
29     89
30     46
31     12
32     67
33     71
34     33
35     90
36      9
37     73
38     66
39     29
40     47
41     77
42     46
43     99
44     34
45     59
46     44
47     78
48     81
49     15

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

NameError: name 'X' is not defined

In [25]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=101)

In [26]:
X_train.shape

(35, 3)

In [28]:
X_train.shape

(35, 3)

In [29]:
X.test.shape

NameError: name 'X' is not defined

In [30]:
X_test.shape

(15, 3)

In [31]:
cd ..

/Users/harishankar/Documents/Work/Chennai


In [32]:
cd ..

/Users/harishankar/Documents/Work


In [33]:
ls

Altisource/           Oracle Integration/   functions.xlsx
Chennai/              Rules/                mongodb/
Deep Learning/        Testing/              oracle/
HackerRank/           UI/                   oracle-batch-service/
NLP/                  Visuallization/       python/
OCR/                  devops/               tw/


In [34]:
cd ../udemy/

/Users/harishankar/Documents/udemy


In [35]:
ll

total 0
drwxr-xr-x@ 16 harishankar  staff  512 Nov  5  2017 Tensorflow-Bootcamp-master/
drwxrwxrwx  19 harishankar  staff  608 Jun 24 09:17 [FreeTutorials.Us] Udemy - complete-guide-to-tensorflow-for-deep-learning-with-python/
drwx------@ 21 harishankar  staff  672 Jun 22 14:25 [FreeTutorials.Us] Udemy - python-the-complete-python-developer-course/
drwxrwxrwx  11 harishankar  staff  352 Jun 22 11:51 cs224d/
drwxr-xr-x@ 12 harishankar  staff  384 Jun 22 13:36 natural-language-processing-with-deep-learning-in-python/


In [36]:
cd ..

/Users/harishankar/Documents


In [37]:
cd ..

/Users/harishankar


In [38]:
cd Documents/Work/Chennai/

/Users/harishankar/Documents/Work/Chennai


In [39]:
ll

total 0
drwxr-xr-x   7 harishankar  staff  224 Jun 26 12:36 ChatBot/
drwxr-xr-x  16 harishankar  staff  512 Nov  5  2017 Tensorflow-Bootcamp-master/


In [40]:
cd Tensorflow-Bootcamp-master/

/Users/harishankar/Documents/Work/Chennai/Tensorflow-Bootcamp-master


In [41]:
ll

total 400
drwxr-xr-x  10 harishankar  staff     320 Nov  5  2017 00-Crash-Course-Basics/
drwxr-xr-x   4 harishankar  staff     128 Nov  5  2017 01-Neural-Network-Basics/
drwxr-xr-x  20 harishankar  staff     640 Nov  5  2017 02-TensorFlow-Basics/
drwxr-xr-x   9 harishankar  staff     288 Nov  5  2017 03-Convolutional-Neural-Networks/
drwxr-xr-x  26 harishankar  staff     832 Nov  5  2017 04-Recurrent-Neural-Networks/
drwxr-xr-x  12 harishankar  staff     384 Nov  5  2017 05-Autoencoders/
drwxr-xr-x   5 harishankar  staff     160 Nov  5  2017 06-Generative-Adversarial-Networks/
drwxr-xr-x  10 harishankar  staff     320 Nov  5  2017 07-Reinforcement-Learning-OpenAI/
drwxr-xr-x   8 harishankar  staff     256 Nov  5  2017 Miscellaneous-Topics/
-rwxr-xr-x@  1 harishankar  staff      25 Nov  5  2017 README.md*
-rwxr-xr-x   1 harishankar  staff  192512 Nov  5  2017 db.sqlite3*
-rwxr-xr-x   1 harishankar  staff    1808 Nov  5  2017 linux_mac_tfdl_env.yml*
-rwxr-xr-x   1 harishankar  staff    1

In [42]:
cd 00-Crash-Course-Basics/

/Users/harishankar/Documents/Work/Chennai/Tensorflow-Bootcamp-master/00-Crash-Course-Basics


In [43]:
ll

total 488
-rwxr-xr-x  1 harishankar  staff  13228 Nov  5  2017 00-NumPy-Crash-Course-Overview.ipynb*
-rwxr-xr-x  1 harishankar  staff   9565 Nov  5  2017 01-Pandas-Crash-Course.ipynb*
-rwxr-xr-x  1 harishankar  staff  80405 Nov  5  2017 02-Data-Viz-Crash-Course.ipynb*
-rwxr-xr-x  1 harishankar  staff   9271 Nov  5  2017 03-SciKit-Learn-Overview.ipynb*
-rwxr-xr-x  1 harishankar  staff  58894 Nov  5  2017 05-Crash-Course-Review-Exercises-Solutions.ipynb*
-rwxr-xr-x  1 harishankar  staff  58045 Nov  5  2017 05-Crash-Course-Review-Exercises.ipynb*
-rwxr-xr-x  1 harishankar  staff     61 Nov  5  2017 salaries.csv*


In [44]:
05-Crash-Course-Review-Exercises.ipynb

SyntaxError: invalid token (<ipython-input-44-f9af38c0dd3f>, line 1)

In [46]:
import numpy as np

In [48]:
np.linspace(-10,10,100)

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

In [50]:
import numpy as np
n_features = 10

In [53]:
np.random.random([1,n_features])
                

array([[ 0.5664905 ,  0.42324267,  0.72013848,  0.54455285,  0.39683686,
         0.92788305,  0.36448055,  0.1135404 ,  0.72328066,  0.4201303 ]])

In [55]:
np.random.random()

<function RandomState.random_sample>